version: '3'
services:
  web:
    image: 585172581592.dkr.ecr.ap-southeast-1.amazonaws.com/vly1-main-repo:latest
    depends_on:
      - db
    ports:
      - "${WEB_PORT:-80}:8000"
    environment:
      NODE_ENV: production
      MONGO_URL: mongodb+srv://vly-client:ZhF3BUDiwpy8C3xK@vly-cluster-1-dl1mj.mongodb.net/test?retryWrites=true

